apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  storageClassName: ebs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
